#!/usr/bin/env python3
import pathlib, sys
if len(sys.argv)!=5:
    print('usage: stage24474_rubber_warmstart_integration_contract.py <build.ps1> <cpp> <test.ps1> <native-audit.py>')
    raise SystemExit(2)
build=pathlib.Path(sys.argv[1]).read_text(encoding='utf-8-sig',errors='replace')
cpp=pathlib.Path(sys.argv[2]).read_text(encoding='utf-8-sig',errors='replace')
test=pathlib.Path(sys.argv[3]).read_text(encoding='utf-8-sig',errors='replace')
native=pathlib.Path(sys.argv[4]).read_text(encoding='utf-8-sig',errors='replace')
print('ANGRY_STAGE24_47_4_RUBBER_WARMSTART_INTEGRATION_CONTRACT 1')
print('policy=DIAGNOSTIC_ONLY; no contact/joint/body/Lua mutation')
print('goal=separate manifold warm-start carryover from finalized impulses and integration clamps after Stage47.3 closed the core high-restitution normal solver')
checks=[]
def gate(n,v):
    checks.append((n,bool(v))); print(f'{n}={"PASS" if v else "FAIL"}')
gate('runtime_contact_prestep_present','[stage24.47.4-warm] CONTACT_PRE' in cpp)
gate('runtime_presolve_after_contact_update_present','[stage24.47.4-warm] PRESOLVE' in cpp and 'observeRubberPreSolve24474(contact, oldManifold);' in cpp)
gate('runtime_contact_poststep_present','[stage24.47.4-warm] CONTACT_POST' in cpp)
gate('runtime_body_poststep_present','[stage24.47.4-integrate] BODY_POST' in cpp)
gate('runtime_manifold_impulses','warmNormal' in cpp and 'finalNormal' in cpp and 'normalImpulse' in cpp and 'tangentImpulse' in cpp)
gate('runtime_linear_cap','linearCandidate' in cpp and 'linearCap' in cpp and 'b2_maxTranslation' in cpp)
gate('runtime_angular_cap','rotationCandidate' in cpp and 'angularCap' in cpp and '0.5f * b2_pi' in cpp)
gate('postsolve_timing_caveat','POSTSOLVE_ISLAND_REPORT_AFTER_INTEGRATION_CLAMPS' in cpp)
gate('native_audit_wired','stage24474_rubber_warmstart_integration_native_audit.py' in build and 'stage24.47.4-rubber-warmstart-integration-native-audit.txt' in build)
gate('native_targets_remaining_paths', all(x in native for x in ('b2Contact::Update','FinalizeVelocityConstraints','b2Island::Solve','b2Island::Report','b2World::Step')))
gate('egg2_test','LevelGE_2' in test and 'ExtraRubberBall' in test)
gate('8_3_test','LevelP3_306' in test and '8-3' in test)
gate('stage473_retained','stage24473_high_restitution_contact_solver_audit_contract.py' in build)
gate('stage472_retained','stage24472_distance_joint_spring_audit_contract.py' in build)
gate('fixed_step_retained','world.Step(dt, 10, 10);' in cpp)
start=cpp.find('static void manifoldImpulseSums24474')
end=cpp.find('bool isRubberJoint24472', start)
block=cpp[start:end] if start>=0 and end>start else ''
mutators=('SetLinearVelocity(','SetAngularVelocity(','ApplyImpulse(','ApplyForce(','SetRestitution(','SetFriction(','CreateJoint(','DestroyJoint(','SetTransform(','SetPosition(','SetWarmStarting(')
gate('observer_no_physics_mutators', bool(block) and not any(x in block for x in mutators))
gate('no_level_specific_physics_branch','LevelGE_2' not in block and 'LevelP3_306' not in block and 'ExtraRubberBall' not in block and 'ExtraTrampoline' not in block)
ok=all(v for _,v in checks)
print('verdict='+('PASS' if ok else 'FAIL'))
raise SystemExit(0 if ok else 1)
